CC=g++
CXXFLAGS=-Ofast -march=native -mtune=native -fomit-frame-pointer -I include/
LDFLAGS=-lm -lSDL2

SOURCES=$(wildcard src/*.cpp)
OBJECTS=$(SOURCES:.cpp=.o)

all: spn

spn: $(OBJECTS)
	$(CC) -o spn $(OBJECTS) $(LDFLAGS)

src/%.o: src/%.cpp include/%.hpp
	$(CC) $(CXXFLAGS) -o $@ -c $<

run: spn
	SDL_VIDEODRIVER=wayland ./spn test.scn

runx: spn
	./spn test.scn

clean:
	$(info Cleaning)
	rm -rf $(OBJECTS) spn
